.\" Generated with Ronnjs 0.4.0
.\" http://github.com/kapouer/ronnjs
.
.TH "BABELWEB\-CHANGELOG" "1" "April 2013" "" ""
.
.SH "NAME"
\fBbabelweb-changelog\fR \-\- Changes
.
.SH "HISTORY"
.
.SS "0\.3\.0 (not released yet)"
.
.IP "\(bu" 4
Support for monitoring multiple babel routers
.
.IP "\(bu" 4
INCOMPATIBLE CHANGE: command\-line option renaming
.
.IP "\(bu" 4
Ignore duplicate changes to reduce network traffic
.
.IP "\(bu" 4
Set server\-side process title to babelweb
.
.IP "\(bu" 4
Fix various bugs and glitches in client\-side UI
.
.IP "\(bu" 4
Bump every dependency to latest version (Node\.js, socket\.io, D3\.js)
.
.IP "" 0
.
.SS "0\.2\.4"
.
.IP "\(bu" 4
Use the latest release of D3
.
.IP "\(bu" 4
Fix install dependencies for npm
.
.IP "\(bu" 4
Change jussieu\.fr to univ\-paris\-diderot\.fr
.
.IP "" 0
.
.SS "0\.2\.3"
.
.IP "\(bu" 4
Security fix: properly drop privileges (thanks to Julien Cristau)
.
.IP "" 0
.
.SS "0\.2\.2"
.
.IP "\(bu" 4
Security fix: refuse to run as root
.
.IP "" 0
.
.SS "0\.2\.1"
.
.IP "\(bu" 4
Fix legend color for unreachable neighbours
.
.IP "" 0
.
.SS "0\.2\.0"
.
.IP "\(bu" 4
Fix rendering model (and many bugs)
.
.IP "\(bu" 4
Do not randomize on zoom
.
.IP "\(bu" 4
Change colors and add a legend
.
.IP "\(bu" 4
Use a logarithmic scale (more stable graph)
.
.IP "\(bu" 4
Do not display redundant routes (faster)
.
.IP "\(bu" 4
Enable volatile updates
.
.IP "\(bu" 4
Fix html markup and minor details in the interface
.
.IP "" 0
.
.SS "0\.1\.0"
.
.IP "\(bu" 4
Switch to the d3\.js library, improve UI
.
.IP "\(bu" 4
Make npm package
.
.IP "\(bu" 4
Write documentation
.
.IP "\(bu" 4
Work\-around bugs in babeld and babelz
.
.IP "" 0
.
.SS "0\.0\.0"
.
.IP "\(bu" 4
First sketch using protovis and jquery
.
.IP "\(bu" 4
Core layout established
.
.IP "" 0

