.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "BABELWEB\-CHANGELOG" "1" "August 2011" "" ""
.
.SH "NAME"
\fBbabelweb-changelog\fR \-\- Changes
.
.SH "HISTORY"
.
.SS "0\.1 (not released)"
.
.IP "\(bu" 4
Switch to the d3\.js library, improve UI
.
.IP "\(bu" 4
Make npm package
.
.IP "\(bu" 4
Write documentation
.
.IP "\(bu" 4
Work\-around bugs in babeld and babelz
.
.IP "" 0
.
.SS "0\.0"
.
.IP "\(bu" 4
First sketch using protovis and jquery
.
.IP "\(bu" 4
Core layout established
.
.IP "" 0

