.\" Generated with Ronnjs 0.3.8
.\" http://github.com/kapouer/ronnjs/
.
.TH "BABELWEB" "1" "June 2014" "" ""
.
.SH "NAME"
\fBbabelweb\fR \-\- monitoring tool for babel
.
.SH "SYNOPSIS"
.
.nf
babelweb [options]
.
.fi
.
.SH "DESCRIPTION"
Babelweb is a web\-based monitoring tool for the Babel routing daemon\.  It
reads informations from \fBbabeld\fR through a local\-interface socket (see the \fB\-g\fR
option of \fBbabeld\fR)\.
.
.SH "OPTIONS"
Options are a list of \fBkey=value\fR pairs\.
.
.IP "\(bu" 4
\fBhost\fR:
local webserver address (default: \fB::\fR)\.
.
.IP "\(bu" 4
\fBport\fR:
local webserver port (default: \fB8080\fR)\.
.
.IP "\(bu" 4
\fBrouters\fR:
comma\-separated list of addresses and ports, specifying the local interfaces \fBbabeld\fR is listening on (default: \fB[::1]:33123\fR)\.
.
.IP "\(bu" 4
\fBupdate\fR:
time between updates to the browser, in milliseconds (default: \fB3000\fR)\.
.
.IP "\(bu" 4
\fBverbose\fR:
(very) verbose output (default: \fBfalse\fR)\.
.
.IP "" 0
.
.SH "Client\-side configuration"
Configuration of the web interface, such as the correspondance between
hostnames and router\-ids, is done in the file \fBjs/site\-local\.js\fR\|\.  See \fBjs/site\-local\.js\.sample\fR for a sample configuration\.
.
.SH "SECURITY"
Running as root is not necessary, and not recommended anymore\.
.
.SH "SIGNALS"
Babelweb reacts to the SIGUSR1 and SIGUSR2 signals:
.
.IP "\(bu" 4
SIGUSR1:
dump the topology of each router as seen by babelweb (json format)\.
.
.IP "\(bu" 4
SIGUSR2:
restart connections to \fBbabeld\fR\|\.
.
.IP "" 0
.
.SH "BUGS"
When you find issues, please report them:
.
.IP "\(bu" 4
web: \fIhttp://github\.com/kerneis/babelweb/issues\fR
.
.IP "\(bu" 4
email:
Babel users mailing\-list \fIbabel\-users@lists\.alioth\.debian\.org\fR
Gabriel Kerneis \fIkerneis@pps\.univ\-paris\-diderot\.fr\fR
.
.IP "" 0
.
.P
If possible, try to reproduce the bug with the \fBverbose=true\fR option and
include the output in your report\.
.
.P
You can also look for kerneis in ##babel on irc://irc\.freenode\.net\.
.
.SH "SEE ALSO"
babelweb\-changelog(1), babeld(8)\.
.
.SH "AUTHOR"
Gabriel Kerneis \fIgabriel@kerneis\.info\fR
